<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container19zPiXt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container19zPiXt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container19zPiXt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container19zPiXt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container19zPiXt\App_KernelDevDebugContainer([
    'container.build_hash' => '19zPiXt',
    'container.build_id' => '0d31bfc6',
    'container.build_time' => 1690895965,
], __DIR__.\DIRECTORY_SEPARATOR.'Container19zPiXt');
